/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 19 15:05:02 GMT 2026
 */

package sbst.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sbst.calculator.CalculatorService;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CalculatorService_ESTest extends CalculatorService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = CalculatorService.isValidOperator('*');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CalculatorService calculatorService0 = new CalculatorService();
      // Undeclared exception!
      try { 
        calculatorService0.calculate(0.0, 0.0, 'W');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Operador inv\u00E1lido.
         //
         verifyException("sbst.calculator.CalculatorService", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CalculatorService calculatorService0 = new CalculatorService();
      double double0 = calculatorService0.calculate(190.0, (-2447.549525), '*');
      assertEquals((-465034.40975), double0, 0.01);
  }
}
